[package]
name = "daddys-pos"
version = "1.0.0"
description = "DADDY's Bakery POS"
authors = ["DADDY's Bakery"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.70"

[lib]
name = "daddys_pos_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
